### ISSUE TITLE
Add sensible dotfiles

### ISSUE THREAD

**Issue by simonplend** [financial-times-sandbox/tako#11]
- [x] `.editorconfig`
- [x] `tslint.json`
- [x] `.gitignore`
- [x] `.nvmrc`
- [x] `.npmrc`

**Comment by simonplend** [comment]
These can probably be pinched from [n-gage/dotfiles](https://github.com/Financial-Times/n-gage/tree/master/dotfiles) and tweaked / slimmed down (especially in the case of `eslintrc.js`).

**Comment by sjparkinson** [comment]
Dare I suggest prettier?

**Comment by adambraimbridge** [comment]
I have no objections

**Comment by adambraimbridge** [comment]
I added `.nvmrc` but I'm not married to it, if anyone has objections

**Comment by simonplend** [comment]
Just realised we'd want `tslint`, not `eslint` :wink:

**Comment by simonplend** [comment]
The Probot repo itself is nicely setup: https://github.com/probot/probot

Things I noticed:

- [.npmrc](https://github.com/probot/probot/blob/master/.npmrc)
- [tslint.json](https://github.com/probot/probot/blob/master/tslint.json)
- [tsconfig.json](https://github.com/probot/probot/blob/master/tsconfig.json)
