### ISSUE TITLE
Use `n-logger` for logging 

### ISSUE THREAD

**Issue by adambraimbridge** [financial-times-sandbox/tako#29]
There's a [logger built into probot](https://github.com/probot/probot/blob/master/src/logger.ts), but it doesn't send logs to splunk. `n-logger` does. 

![image](https://user-images.githubusercontent.com/224547/47021151-cc4e3100-d152-11e8-8952-2f0608f9cb1e.png)

**Comment by simonplend** [comment]
Related: #5.

**Comment by sjparkinson** [comment]
Closing as duplicate of #5.
